javascript:(function(){
    var w = window.open();
    w.document.write('<!DOCTYPE html><html><head><title>Compile Dolphin to WASM</title></head><body>');
    w.document.write('<h1>Compile Dolphin Emulator to WASM</h1>');
    w.document.write('<button onclick="startCompilation()">Start Compilation</button>');
    w.document.write('<p id="status"></p>');
    w.document.write('<iframe id="emceptionFrame" src="https://jprendes.github.io/emception/" width="100%" height="500px"></iframe>');
    w.document.write('<a id="downloadLink" style="display:none" download>Download Compiled Files</a>');
    w.document.write('<script>');
    w.document.write('function startCompilation() {');
    w.document.write('document.getElementById("status").innerText = "Initializing Emception...";');
    w.document.write('const frame = document.getElementById("emceptionFrame");');
    w.document.write('frame.contentWindow.postMessage({action: "compile", repo: "https://github.com/dolphin-emu/dolphin"}, "*");');
    w.document.write('}');
    w.document.write('window.addEventListener("message", function(event) {');
    w.document.write('if (event.origin !== "https://jprendes.github.io") return;');
    w.document.write('if (event.data.status === "success") {');
    w.document.write('document.getElementById("status").innerText = "Compilation complete. Downloading files...";');
    w.document.write('fetchCompiledFiles(event.data.outputUrl);');
    w.document.write('} else if (event.data.status === "error") {');
    w.document.write('document.getElementById("status").innerText = "Error: " + event.data.message;');
    w.document.write('}');
    w.document.write('});');
    w.document.write('function fetchCompiledFiles(url) {');
    w.document.write('const downloadLink = document.getElementById("downloadLink");');
    w.document.write('downloadLink.href = url;');
    w.document.write('downloadLink.innerText = "Download Compiled Files";');
    w.document.write('downloadLink.style.display = "block";');
    w.document.write('}');
    w.document.write('<\/script></body></html>');
})();
